swagger: '2.0'
info:
  description: >-
    "TCL4 will require the submission of test data.  Some of these data are not
    readily collected via UTM means. This file describes the endpoints used for
    that data collection.  These models are referenced in the Data Management
    Plan (DMP), so this API and associated models are referred to using the
    acronym 'DMP'"
  version: '0.1'
  title: "API endpoints for TCL4 data collection"
  termsOfService: >

    A. No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
    WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING,
    BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO
    SPECIFICATIONS, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
    PARTICULAR PURPOSE, OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE
    SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF
    PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN
    ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR
    RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR
    ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE. FURTHER,
    GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES REGARDING
    THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND DISTRIBUTES
    IT "AS IS."


    B. Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
    AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS
    WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT''S USE OF THE SUBJECT SOFTWARE
    RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING
    FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING
    FROM, RECIPIENT''S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY
    AND HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
    SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY
    LAW. RECIPIENT''S SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE,
    UNILATERAL TERMINATION OF THIS AGREEMENT.
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utm.arc.nasa.gov/'
    email: joseph.rios@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'

host: utmregistry.arc.nasa.gov.
basePath: /api/v4
schemes:
  - https

securityDefinitions:
  ussapi_security:
    type: oauth2
    tokenUrl: 'https://utm.defined.host/oauth/token'
    flow: application
    scopes:
      'utm.nasa.gov_write.message': Subject can read, create, and update message data such as UTM Message and Negotiations and DMP data

paths:
  '/delete-by-callsign-run-model':
    delete:
      summary: Delete ALL data for a particular (callsign, run, model) triple.
      description: |-
        This endpoint should be used with care. If the USS owns the data for
        a particular callsign-run pairing, then it can request to delete all
        previously submitted data for a given model. This is usually needed
        if a USS catches a problem with the data that it submitted and needs
        to fix the error in its data and resubmit.

        Due to the way in which data are processed on the backend, a USS MUST
        wait an hour after a successful call to this endpoint before trying
        to submit the replacement data.  This is due to the potential for the
        replacement data to get persisted prior to the DELETE being executed.

        Note that this deletes ALL records for a given model for that callsign
        and run.  So if only a particular instance was 'bad' the USS would need
        to re-send all instances with the fixed instance in order to ensure
        completeness of data.

        Ideally, the USS will notify NASA of the need to use this endpoint
        prior to calling it so that we can monitor the data processes on the
        backend.
      security:
        - ussapi_security:
            - utm.nasa.gov_write.message
      parameters:
        - in: body
          name: DeleteDmpData
          required: true
          schema:
            $ref: '#/definitions/CallsignRunModel'

      responses:
        '202':
          description: Accepted. Assume success, but verify with NASA.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '401':
          description: Invalid or missing access_token provided.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '403':
          description: Forbidden. Do not retry with same access token. Reason not provided, but do you have the right scopes? Does uss_name match the sub claim?
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
definitions:
  CallsignRunModel:
    description: >-
      The callsign, run, and model to be be deleted.
    type: object
    required:
      - call_sign
      - test_run
      - model
    example:
      call_sign: Viper1
      test_run: 2045
      model: FlightEssentialTelemetryAndUasStates
    properties:
      call_sign:
        type: string
        minLength: 1
        maxLength: 100
        description: >-
          A UTM TCL4 globally unique identifier that is associated with a vehicle/operation
          Every operation requires a call_sign that is pre-determined in the
          full test card description.
      test_run:
        description: >-
          An identifier for a specific run of a test_card.  In many cases, a
          test_card may be only run once.  However, it is possible that a
          test_card is run multiple times.
        type: integer
      model:
        description: >-
          The model that is to be deleted for this call_sign and test_run.
        type: string
        enum:
          - OffNominalReport
          - LossOfUss
          - USSHandoff
          - USSNegotiation
          - USS2OperatorExchange
          - DynamicRestrictionOccurrence
          - USSExchange
          - Waypoint
          - AuxiliaryUASOperation
          - CnsPreRun
          - UasTruthPosition
          - EmergencyPhase
          - OffNominalMitigationOutcome
          - LandingOutcome
          - SafeToLandLocationReach
          - OnBoardSafeLandingCapability
          - ConPreRunRange
          - ConPreRunOp
          - ConActualLanding
          - ConWxOperatingPointData
          - ConWxOperatingPointDataStation
          - CellServiceAvailability
          - DistressV2V
          - RpicConstraintMessage
          - DaaGeoFence
          - DaaSensor
          - DaaSensorV2V
          - StaticObstacleTable
          - ConflictResolutionConfiguration
          - DaaSensorAccuracyRealTime
          - DaaSensorV2vData
          - DaaSensorNumberOfLostTracks
          - DaaSensorTimeToTrack
          - DaaSensorIntruderAircraftDetection
          - DaaSensorObstacle
          - DaaConflictResolutionMeasurement
          - FlightEssentialTelemetryLatency
          - FlightEssentialTelemetryAndUasStates
          - RemoteID
