info:
  version: "v1.0"
  title: UTM DMP TCL4 CNS
  description: Data model for CNS submission.
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utmregistry.arc.nasa.gov/'
    email: jaewoo.jung@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'
  termsOfService: >-
    A. No Warranty: THE SUBJECT SOFTWARE IS PROVIDED \"AS IS\" WITHOUT ANY
    WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING,
    BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO
    SPECIFICATIONS, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
    PARTICULAR PURPOSE, OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE
    SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF
    PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN
    ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR
    RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR
    ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE. FURTHER,
    GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES REGARDING
    THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND DISTRIBUTES
    IT \"AS IS.\"
    B. Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
    AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS
    WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT''S USE OF THE SUBJECT SOFTWARE
    RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING
    FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING
    FROM, RECIPIENT''S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY
    AND HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
    SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY
    LAW. RECIPIENT''S SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE,
    UNILATERAL TERMINATION OF THIS AGREEMENT.
swagger: '2.0'

paths:
  '/no-paths':
    put:
      responses:
        '410':
          description: >-
            Gone. Not implemented. Will not be implemented. Path included for
            proper use by automated tooling.  Tools sometimes do not like
            when there are no paths, but domains do not contain paths.
definitions:
  CnsPreRun:
    type: object
    required:
      - "metaData"
      - "minimumAircraftToOperatorDataTransferRateForOperation_bytesPerSec"
      - "minimumOperatorToAircraftDataTransferRateForOperation_bytesPerSec"
      - "maximumAircraftToOperatorRoundTripLatencyTolerableForOperation_ms"
      - "maximumOperatorToAircraftRoundTripLatencyTolerableForOperation_ms"
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      minimumAircraftToOperatorDataTransferRateForOperation_bytesPerSec:
        description: >-
          "Report the minimum aircraft to operator data transfer rate (in Bytes
          per second) necessary to execute the operation. Consider that data
          should be authenticated and checked for integrity. (bytesPerSec)"
        type: integer
        format: int32
        minimum: 0
      minimumOperatorToAircraftDataTransferRateForOperation_bytesPerSec:
        description: >-
          "Report the minimum operator to aircraft data transfer rate (in Bytes
          per second) necessary to execute the operation. Consider that data
          should be authenticated and checked for integrity. (bytesPerSec)"
        type: integer
        format: int32
        minimum: 0
      maximumAircraftToOperatorRoundTripLatencyTolerableForOperation_ms:
        description: >-
          "Report the maximum tolerable Round-trip latency from source to
          destination to execute the operation, in millisecond (ms)"
        type: integer
        format: int32
        minimum: 0
      maximumOperatorToAircraftRoundTripLatencyTolerableForOperation_ms:
        description: >-
          "Report the maximum tolerable Round-trip latency from source to
          destination to execute the operation, in millisecond (ms)"
        type: number
        format: int32
        minimum: 0

  UasTruthPosition:
    description: >-
      As reported by truth position system 
    type: object
    required:
      - "metaData"
      - "xCoordinate_ft"
      - "yCoordinate_ft"
      - "zCoordinate_ft"
      - "timestamp"
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      xCoordinate_ft:
        description: "X-Coordinate truth position of UA (ECEF: Earth Centered Earth\
          \ Fixed, inch-level resolution);\nas reported by the Ground Truth System\
          \ (Truth Reference System, e.g. optical, radar, LiDAR, nav. beacon, etc).\n\
          Can be reported by the UAS but has to be independent of UAS's primary navigation\
          \ system,\nuse of separate RTK system is allowed (UTC time stamped).\nReport\
          \ at least 2 decimal places of precision. (ft)"
        $ref: "#/definitions/UasTruthEcefCoordinate_ft"
      yCoordinate_ft:
        description: "Y-Coordinate truth position of UA (ECEF: Earth Centered Earth\
          \ Fixed, inch-level resolution);\nas reported by the Ground Truth System\
          \ (Truth Reference System, e.g. optical, radar, LiDAR, nav. beacon, etc).\n\
          Can be reported by the UAS but has to be independent of UAS's primary navigation\
          \ system,\nuse of separate RTK system is allowed (UTC time stamped).\nReport\
          \ at least 2 decimal places of precision. (ft)"
        $ref: "#/definitions/UasTruthEcefCoordinate_ft"
      zCoordinate_ft:
        description: "Z-Coordinate truth position of UA (ECEF: Earth Centered Earth\
          \ Fixed, inch-level resolution);\nas reported by the Ground Truth System\
          \ (Truth Reference System, e.g. optical, radar, LiDAR, nav. beacon, etc).\n\
          Can be reported by the UAS but has to be independent of UAS's primary navigation\
          \ system,\nuse of separate RTK system is allowed (UTC time stamped).\nReport\
          \ at least 2 decimal places of precision. (ft)"
        $ref: "#/definitions/UasTruthEcefCoordinate_ft"
      timestamp:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/timestamp'

  UasTruthEcefCoordinate_ft:
    type: "object"
    required:
    - "estimatedError95Prct_in"
    - "value_ft"
    properties:
      value_ft:
        type: "number"
        format: "double"
        description: "Coordinate value (ft)"
        example: 871.94
      estimatedError95Prct_in:
        type: "number"
        format: "double"
        description: >-
          "Estimated truth system position (ECEF) error at time of measurement
          (95 percentile, inches). UTC time stamped. (in)"
        minimum: 0.0
        example: 3.2

  EmergencyPhase:
    description: >-
      "During operation, operator must monitor UA operation according
       to Communications and Navigation Procedure (Reference 9, Section 4.2)
       and report appropriate emergency phase with UTC timestamp as enum"
    type: object
    required:
      - "metaData"
      - "timestamp"
      - "emergencyPhaseValue"
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      timestamp:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/timestamp'
      emergencyPhaseValue:
        type: string
        enum:
          - "NOMINAL"
          - "UNCERTAINTY"
          - "ALERT"
          - "DISTRESS"

  OffNominalMitigationOutcome:
    description: >-
      Outcome of offnominal events like UA to Operator C2 Link Loss, Operator
      to UA C2 Link Loss, or Loss of Vehicle Navigation, is reported as enum:
      * Resolved_within_operation_volume,
      * Resolved_but_triggered_nonconforming_state,
      * Resolved_but_triggered_rogue_state,
      * Unresolved_vehicle_flew_away,
      * Unresolved_vehicle_crashed_to_ground,
      * Unresolved_vehicle_collided_with_another_vehicle,
      * Unresolved_vehicle_collided_with_building
    type: object
    required:
      - metaData
      - timestamp
      - offNominalMitigationOutcomeValue
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      timestamp:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/timestamp'
      offNominalMitigationOutcomeValue:
        type: "string"
        enum:
          - "RESOLVED_WITHIN_OPERATION_VOLUME"
          - "RESOLVED_BUT_TRIGGERED_NONCONFORMING_STATE"
          - "RESOLVED_BUT_TRIGGERED_ROGUE_STATE"
          - "UNRESOLVED_VEHICLE_FLEW_AWAY"
          - "UNRESOLVED_VEHICLE_CRASHED_TO_GROUND"
          - "UNRESOLVED_VEHICLE_COLLIDED_WITH_ANOTHER_VEHICLE"
          - "UNRESOLVED_VEHICLE_COLLIDED_WITH_BUILDING"

  LandingOutcome:
    type: object
    required:
      - "metaData"
      - "timestamp"
      - "landingOutcomeValue"
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      timestamp:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/timestamp'
      landingOutcomeValue:
        type: "string"
        description: >-
          "Report this for every landing as enum, landing within
          contingency_polygon is also considered as safe landing."
        enum:
        - "LANDED_SAFELY_WITHIN_OPERATION_VOLUME"
        - "LANDED_SAFELY_OUTSIDE_OF_OPERATION_VOLUME"
        - "LANDED_UNSAFELY_WITHIN_OPERATION_VOLUME"
        - "LANDED_UNSAFELY_OUTSIDE_OF_OPERATION_VOLUME"

  SafeToLandLocationReach:
    type: object
    required:
      - "metaData"
      - "timestamp"
      - "canReachSafeToLandLocation"
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      timestamp:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/timestamp'
      canReachSafeToLandLocation:
        type: "boolean"
        description: >-
          "Operator to select true/false to indicate whether UA can reach
          designated safe-to-reach location: For example, if battery is too low
          or wind is too strong for UA to reach safe to land location, 'false'
          should be selected."
        example: true

  OnBoardSafeLandingCapability:
    type: object
    required:
      - "metaData"
      - "timestamp"
      - "onBoardSafeLandingCapabilityStatus"
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      timestamp:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.5/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/timestamp'
      onBoardSafeLandingCapabilityStatus:
        type: "string"
        description: >-
          "Operator to select one of the following enum to indicate whether UA's
          onboard safe landing capability (i.e. onboard system that is capable
          of identifying safe to land location and land while avoiding people
          and property, such as safe2ditch) is working properly or not.  For
          example, if the onboard safe landing system uses optical sensor and a
          bug has rendered it non-usable, (onboard safe landing system is
          compromised) should be selected."
        enum:
        - "ONBOARD_SAFE_LANDING_SYSTEM_FUNCTIONING_NORMALLY"
        - "ONBOARD_SAFE_LANDING_SYSTEM_IS_COMPROMISED"
        - "UA_NOT_EQUIPPED_WITH_ONBOARD_SAFE_LANDING_SYSTEM"
