swagger: '2.0'
info:
  description: >-
    "TCL4 requires the submission of vehicle-centric data including from specialized sensors mounted on the vehicle which may collect data at various sampling rates.  These models are referenced in the Data Management Plan (DMP)."
  version: 'v1.0'
  title: "API endpoints for UTM TCL DMP CON vehicles data collection"
  termsOfService: >

    A. No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
    WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING,
    BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO
    SPECIFICATIONS, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
    PARTICULAR PURPOSE, OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE
    SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF
    PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN
    ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR
    RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR
    ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE. FURTHER,
    GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES REGARDING
    THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND DISTRIBUTES
    IT "AS IS."


    B. Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
    AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS
    WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT''S USE OF THE SUBJECT SOFTWARE
    RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING
    FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING
    FROM, RECIPIENT''S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY
    AND HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
    SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY
    LAW. RECIPIENT''S SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE,
    UNILATERAL TERMINATION OF THIS AGREEMENT.
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utm.arc.nasa.gov/'
    email: joseph.rios@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'

host: utmregistry.arc.nasa.gov.
basePath: /api/v4
schemes:
  - https

securityDefinitions:
  ussapi_security:
    type: oauth2
    tokenUrl: 'https://utm.defined.host/oauth/token'
    flow: application
    scopes:
      'utm.nasa.gov_write.message': Subject can create and delete DMP USS and vehicle-centric data

paths:

##
# con-pre-run-range
##
  
  '/con-pre-run-range':
    post:
      summary: Upload a single instance of the ConPreRunRange model.  Only once such instance should be uploaded per run of a test card.
      security:
        - ussapi_security:
            - utm.nasa.gov_write.message
      consumes:
        - application/json
      parameters:
        - in: body
          name: ConPreRunRange
          description: The ConPreRunRange model 
          required: true
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.2/TCL4%20Data%20Management/utm-tcl4-dmp-con.yaml#/definitions/ConPreRunRange
      responses:
        '200':
          description: Data received. No content returned.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '400':
          description: Bad request. Typically validation error. Fix your request and retry.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '401':
          description: Invalid or missing access_token provided.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '403':
          description: Forbidden. Do not retry with same access token. Reason not provided, but do you have the right scopes? Does uss_name match the sub claim?
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse

    delete:
      summary: Delete a previously uploaded instance of ConPreRunRange recorded during a run of a test card
      security:
        - ussapi_security:
            - utm.nasa.gov_write.message
      parameters:
        - in: body
          name: metaDataTestSite
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.2/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaDataTestSite'
          description: DELETE  
      responses:
        '200':
          description: Data received. No content returned.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '401':
          description: Invalid or missing access_token provided.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '403':
          description: Forbidden. Do not retry with same access token. Reason not provided, but do you have the right scopes? Does uss_name match the sub claim?
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '404':
          description: Requested model not found.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse



##
# con-pre-run-op
##
  
  '/con-pre-run-op':
    post:
      summary: Upload a single instance of the ConPreRunOp model.  Only once such instance should be uploaded per (call_sign,test_run) pair.
      security:
        - ussapi_security:
            - utm.nasa.gov_write.message
      consumes:
        - application/json
      parameters:
        - in: body
          name: ConPreRunOp
          description: The ConPreRunOp model 
          required: true
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.2/TCL4%20Data%20Management/utm-tcl4-dmp-con.yaml#/definitions/ConPreRunOp
      responses:
        '200':
          description: Data received. No content returned.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '400':
          description: Bad request. Typically validation error. Fix your request and retry.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '401':
          description: Invalid or missing access_token provided.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '403':
          description: Forbidden. Do not retry with same access token. Reason not provided, but do you have the right scopes? Does uss_name match the sub claim?
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse

    delete:
      summary: Delete a previously uploaded instance of ConPreRunOp recorded during a (call_sign,test_run) pair
      security:
        - ussapi_security:
            - utm.nasa.gov_write.message
      parameters:
        - in: body
          name: metaDataCallSignRun
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.2/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaDataCallSignRun'
          description: DELETE  
      responses:
        '200':
          description: Data received. No content returned.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '401':
          description: Invalid or missing access_token provided.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '403':
          description: Forbidden. Do not retry with same access token. Reason not provided, but do you have the right scopes? Does uss_name match the sub claim?
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
        '404':
          description: Requested model not found.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/nasa/utm-apis/master/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse



