info:
  description: >-
    "TCL4 will require the submission of test data.  Some of these data are not
    readily collected via UTM means.  The models presented in this domain are in
    support of such data that are not readily collected otherwise.  Some of
    these data will be collected live, some after testing, but all should be
    collected as a soon as feasible.  Further details will be provided in other
    testing documentation."
  version: 'v1'
  title: "Domain for Geofence Data used in DAA"
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utm.arc.nasa.gov/'
    email: joseph.rios@nasa.gov
swagger: "2.0"
paths:
  '/no-paths':
    put:
      responses:
        '410':
          description: >-
            Gone. Not implemented. Will not be implemented. Path included for
            proper use by automated tooling.  Tools sometimes do not like
            when there are no paths, but domains do not contain paths.
definitions:
  DaaGeoFence:
    required:
      - metaData
      - geofence_id
      - timestamp
      - enabled
      - start_time
      - end_time
      - type
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/master/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      geofence_id:
        description: >-
          Identifier for this geofence data instance.

          Notes for static geofences:
          1. Expecting a single DaaGeoFence submission for an operation with a
          static geofence.

          2. Timestamp can be any reasonable value.  Expect that it would be earlier
          than the operation start time since the geofence would be defined
          prior to operation commencement.

          Notes for dynamic geofences:
          1. This id should remain constant across multiple geofence samples for a
          dynamic geofence associated with the same metaData model.

          2. Samples for a single metaData model differentiated and ordered by 
          timestamps.
        type: string
        format: uuid
        maxLength: 36
        minLength: 36
        pattern: "^[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-4[0-9a-fA-F]{3}\\-[8-b][0-9a-fA-F]{3}\\-[0-9a-fA-F]{12}$"
        example: "00000000-0000-4444-8888-FEEDDEADBEEF"
      timestamp:
        description: >-
          Time for the sample of this geofence data instance. For a static
          geofence, this may simply be any reasonable time that the geofence
          is defined and/or entered on the platform.  For dynamic geofences,
          this is the sample time for the geofence, likely during the operation
          window.
        type: string
        format: date-time
        minLength: 24
        maxLength: 24
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})Z$"
        example: '2015-08-20T14:11:56.118Z'
      enabled:
        description: >-
          Geofence is enabled.
        type: boolean
        example: true
      start_time:
        description: >-
          UTC Time for start of the geofence. When the geofence is enabled.
        type: string
        format: date-time
        minLength: 24
        maxLength: 24
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})Z$"
        example: '2015-08-20T14:11:56.118Z'
      end_time:
        description: >-
          UTC Time for end of the geofence.  When the geofence is disabled.
        type: string
        format: date-time
        minLength: 24
        maxLength: 24
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})Z$"
        example: '2015-08-20T14:11:56.118Z'
      type:
        description: >-
          The type of geofence.
        type: string
        enum:
          - NONE
          - CIRCULAR-POINT-RADIUS
          - POLYGON
        example: "POLYGON"
      min_altitude:
        description: >-
          Altitude floor of the geofence.
        $ref: 'https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/Altitude'
        example:
          min_altitude:
            altitude_value: 1500
            altitude_reference: "W84"
            units_of_measure: "FT"
      max_altitude:
        description: >-
          Altitude ceiling of the geofence.
        $ref: 'https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/Altitude'
        example:
          max_altitude:
            altitude_value: 1800
            altitude_reference: "W84"
            units_of_measure: "FT"
      circular_geofence_center:
        description: >-
          Circular origin point of the geofence, if circular.
        $ref: 'https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-geojson.yaml#/definitions/Point'
      circular_geofence_radius:
        description: >-
          Radius of circular geofence in ft
        type: number
        format: double
        minimum: 0.0
        example: 200.0
      polygonal_geofence_boundary:
        description: >-
          Geofence boundary if a polygon.
        $ref: 'https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-geojson.yaml#/definitions/Polygon'
