info:
  version: "v1.0"
  title: UTM DMP TCL4 FET
  description: Data model for FET submission.
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utmregistry.arc.nasa.gov/'
    email: abraham.k.ishihara@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'
  termsOfService: >-
    A. No Warranty: THE SUBJECT SOFTWARE IS PROVIDED \"AS IS\" WITHOUT ANY
    WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING,
    BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO
    SPECIFICATIONS, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
    PARTICULAR PURPOSE, OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE
    SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF
    PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN
    ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR
    RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR
    ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE. FURTHER,
    GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES REGARDING
    THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND DISTRIBUTES
    IT \"AS IS.\"


    B. Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
    AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS
    WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT''S USE OF THE SUBJECT SOFTWARE
    RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING
    FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING
    FROM, RECIPIENT''S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY
    AND HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
    SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY
    LAW. RECIPIENT''S SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE,
    UNILATERAL TERMINATION OF THIS AGREEMENT.

swagger: '2.0'

paths:
  '/no-paths':
    put:
      responses:
        '410':
          description: >-
            Gone. Not implemented. Will not be implemented. Path included for
            proper use by automated tooling.  Tools sometimes do not like
            when there are no paths, but domains do not contain paths.

definitions:

  SensorTuple:
    description: >-
      An individual sample of a sensor.  See DMP spreadsheet for definitions of
      the various enum values.

      Each sensor will have its own requirements on sample frequency.
    required:
      - timestamp
      - sensor
      - value
    properties:
      timestamp:
        description: >-
          Time for this sample.
        type: string
        format: date-time
        minLength: 24
        maxLength: 24
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})Z$"
        example: '2015-08-20T14:11:56.118Z'
      value:
        type: number
        format: double
        description: value of sensor reading
      sensor:
        $ref: '#/definitions/SensorList'

  FlightEssentialTelemetryAndUasStates:
    description: >-
      Flight essential telemetry and UAS state data for a UAS Operation in
      TCL4. Refer to the DMP documentation on specific requirements for a given
      run.  Use this model for crewed vehicles as well.  
    required:
      - metaData
      - sensorTuple
    properties:
      metaData:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.6/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaData'
      sensorTuple:
        description: >-
          An array of sensor samples.  Note that the types of samples can be
          mixed in this array.  Also, since time is an element of the sample,
          the samples can be from any variety of times.
        type: array
        items:
          $ref: '#/definitions/SensorTuple'
        minItems: 1
        maxItems: 10000

  MetaDataCallSignRunTsSensor:
    description: >-
      Data model used to delete a fet instance.
    required:
      - metaDataCallSignRun
      - sensor_double
    properties:
      metaDataCallSignRun:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-docs/release-v1.0.6/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/MetaDataCallSignRun'
      sensor_double:
        description: >-
          An array of SensorDouble models to delete
        type: array
        items:
          $ref: '#/definitions/SensorDouble'
        minItems: 1
        maxItems: 10000
    
  SensorList:
    type: string
    enum:
      - LAT
      - LON
      - ALT
      - BAROMETRIC_ALTITUDE_FT
      - EXTERNAL_TEMPERATURE_C
      - RELATIVE_HUMIDITY_PRCT_NONDIM
      - NAVIGATION_ACCURACY_CATEGORY_POSITION
      - NAVIGATION_INTEGRITY_CATEGORY
      - HEADING_DEG
      - TRUE_AIRSPEED_FT_PER_SEC
      - VERTICAL_SPEED_FT_PER_MIN
      - YAW_DEG
      - ROLLRATE_DEG_PER_SEC
      - PITCH_RATE_DEG_PER_SEC
      - YAW_RATE_DEG_PER_SEC
      - VDOP_NONDIM
      - BATTERY_VOLTAGE_V
      - BATTERY_CURRENT_A
      - BATTERY_TEMP_C
      - NUM_GPS_SATELLITES_IN_VIEW_NONDIM
      - MOTOR_10_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_11_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_12_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_13_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_14_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_15_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_16_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_1_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_2_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_3_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_4_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_5_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_6_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_7_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_8_CONTROL_THROTTLE_COMMAND_NONDIM
      - MOTOR_9_CONTROL_THROTTLE_COMMAND_NONDIM
      - NUM_GPS_SAT_NONDIM
      - PITCH_DEG
      - ROLL_DEG
      - TARGET_AIRSPEED_FT_PER_SEC
      - TARGET_GROUND_SPEED_FT_PER_SEC
      - TARGET_WAYPOINT_ALT_FT
      - TARGET_WAYPOINT_LAT_DEG
      - TARGET_WAYPOINT_LON_DEG
      - VEL_DOWN_FT_PER_SEC
      - VEL_EAST_FT_PER_SEC
      - VEL_NORTH_FT_PER_SEC
      - VERTICAL_NAV_POSITION_ERROR_FT
      - VERTICAL_NAV_VELOCITY_ERROR_FT_PER_SEC
      - AIRCRAFT_AIRBORNE_STATE_NONDIM
      - ABOVE_TERRAIN_ALTITUDE_FT
      - GEOMETRIC_VERTICAL_ACCURACY_CATEGORY
      - GROUND_COURSE_DEG
      - GROUND_SPEED_FT_PER_SEC
      - HDOP_NONDIM
      - INDICATED_AIRSPEED_FT_PERSEC
      - LATERAL_NAV_POSITION_ERROR_FT
      - LATERAL_NAV_VELOCITY_ERROR_FT_PER_SEC

  SensorDouble:
    description: >-
    required:
      - timestamp
      - sensor
    properties:
      timestamp:
        description: >-
          Time for this sample.
        type: string
        format: date-time
        minLength: 24
        maxLength: 24
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})Z$"
        example: '2015-08-20T14:11:56.118Z'
      sensor:
        $ref: '#/definitions/SensorList'

      
